/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-18-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Constant {
    

        List<String> aradAIComands = new List<String>{'GET LIST','OPEN REPORT','OPEN DASHBOARD', 'CREATE OPPORTUNITY','CREATE ACCOUNT','CREATE LEAD','SEARCH ACCOUNT','CREATE CONTACT'};


}